// Generated by the Supabase MCP's generate_typescript_types against the
// `contentadmin` project (pfgrbkaloadwgtumkali). Regenerate the same way if
// the schema changes — do not hand-edit the `Database` type below.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  public: {
    Tables: {
      channel_members: {
        Row: {
          channel_id: string;
          created_at: string;
          user_id: string;
        };
        Insert: {
          channel_id: string;
          created_at?: string;
          user_id: string;
        };
        Update: {
          channel_id?: string;
          created_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "channel_members_channel_id_fkey";
            columns: ["channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["id"];
          },
        ];
      };
      channels: {
        Row: {
          cadence: string | null;
          created_at: string;
          dot: string | null;
          id: string;
          name: string;
          sub: string | null;
          youtube_access_token: string | null;
          youtube_channel_id: string | null;
          youtube_connected: boolean;
          youtube_refresh_token: string | null;
          youtube_token_expires_at: string | null;
        };
        Insert: {
          cadence?: string | null;
          created_at?: string;
          dot?: string | null;
          id?: string;
          name: string;
          sub?: string | null;
          youtube_access_token?: string | null;
          youtube_channel_id?: string | null;
          youtube_connected?: boolean;
          youtube_refresh_token?: string | null;
          youtube_token_expires_at?: string | null;
        };
        Update: {
          cadence?: string | null;
          created_at?: string;
          dot?: string | null;
          id?: string;
          name?: string;
          sub?: string | null;
          youtube_access_token?: string | null;
          youtube_channel_id?: string | null;
          youtube_connected?: boolean;
          youtube_refresh_token?: string | null;
          youtube_token_expires_at?: string | null;
        };
        Relationships: [];
      };
      import_batches: {
        Row: {
          ai_draft: boolean;
          channel_id: string | null;
          created_at: string;
          id: string;
          send_for_review: boolean;
          spread_days: number;
        };
        Insert: {
          ai_draft?: boolean;
          channel_id?: string | null;
          created_at?: string;
          id?: string;
          send_for_review?: boolean;
          spread_days?: number;
        };
        Update: {
          ai_draft?: boolean;
          channel_id?: string | null;
          created_at?: string;
          id?: string;
          send_for_review?: boolean;
          spread_days?: number;
        };
        Relationships: [
          {
            foreignKeyName: "import_batches_channel_id_fkey";
            columns: ["channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          author: string;
          body: string;
          created_at: string;
          id: string;
          short_id: string;
        };
        Insert: {
          author: string;
          body: string;
          created_at?: string;
          id?: string;
          short_id: string;
        };
        Update: {
          author?: string;
          body?: string;
          created_at?: string;
          id?: string;
          short_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_short_id_fkey";
            columns: ["short_id"];
            isOneToOne: false;
            referencedRelation: "shorts";
            referencedColumns: ["id"];
          },
        ];
      };
      short_alt_titles: {
        Row: {
          created_at: string;
          id: string;
          short_id: string;
          text: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          short_id: string;
          text: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          short_id?: string;
          text?: string;
        };
        Relationships: [
          {
            foreignKeyName: "short_alt_titles_short_id_fkey";
            columns: ["short_id"];
            isOneToOne: false;
            referencedRelation: "shorts";
            referencedColumns: ["id"];
          },
        ];
      };
      shorts: {
        Row: {
          allow_comments: boolean;
          channel_id: string;
          created_at: string;
          description: string;
          duration_seconds: number | null;
          file_name: string | null;
          file_path: string | null;
          file_size_bytes: number | null;
          id: string;
          made_for_kids: boolean;
          metadata_source: string;
          playlist: string | null;
          slot_at: string | null;
          status: string;
          tags: string[];
          title: string;
          trend_note: string | null;
          trend_score: number | null;
          updated_at: string;
          visibility: string;
        };
        Insert: {
          allow_comments?: boolean;
          channel_id: string;
          created_at?: string;
          description?: string;
          duration_seconds?: number | null;
          file_name?: string | null;
          file_path?: string | null;
          file_size_bytes?: number | null;
          id?: string;
          made_for_kids?: boolean;
          metadata_source?: string;
          playlist?: string | null;
          slot_at?: string | null;
          status?: string;
          tags?: string[];
          title?: string;
          trend_note?: string | null;
          trend_score?: number | null;
          updated_at?: string;
          visibility?: string;
        };
        Update: {
          allow_comments?: boolean;
          channel_id?: string;
          created_at?: string;
          description?: string;
          duration_seconds?: number | null;
          file_name?: string | null;
          file_path?: string | null;
          file_size_bytes?: number | null;
          id?: string;
          made_for_kids?: boolean;
          metadata_source?: string;
          playlist?: string | null;
          slot_at?: string | null;
          status?: string;
          tags?: string[];
          title?: string;
          trend_note?: string | null;
          trend_score?: number | null;
          updated_at?: string;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: "shorts_channel_id_fkey";
            columns: ["channel_id"];
            isOneToOne: false;
            referencedRelation: "channels";
            referencedColumns: ["id"];
          },
        ];
      };
      upload_runs: {
        Row: {
          attempted_at: string;
          error_message: string | null;
          id: string;
          progress_pct: number | null;
          short_id: string;
          state: string;
        };
        Insert: {
          attempted_at?: string;
          error_message?: string | null;
          id?: string;
          progress_pct?: number | null;
          short_id: string;
          state: string;
        };
        Update: {
          attempted_at?: string;
          error_message?: string | null;
          id?: string;
          progress_pct?: number | null;
          short_id?: string;
          state?: string;
        };
        Relationships: [
          {
            foreignKeyName: "upload_runs_short_id_fkey";
            columns: ["short_id"];
            isOneToOne: false;
            referencedRelation: "shorts";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      create_or_join_channel: {
        Args: {
          p_cadence: string;
          p_dot: string;
          p_name: string;
          p_sub: string;
          p_youtube_channel_id: string;
        };
        Returns: {
          cadence: string | null;
          created_at: string;
          dot: string | null;
          id: string;
          name: string;
          sub: string | null;
          youtube_access_token: string | null;
          youtube_channel_id: string | null;
          youtube_connected: boolean;
          youtube_refresh_token: string | null;
          youtube_token_expires_at: string | null;
        }[];
      };
      get_channel_members: {
        Args: { cid: string };
        Returns: {
          email: string;
          joined_at: string;
          user_id: string;
        }[];
      };
      is_channel_member: { Args: { cid: string }; Returns: boolean };
      is_short_member: { Args: { sid: string }; Returns: boolean };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;

// Convenience aliases used throughout the app (not part of the generated
// output — kept here so the rest of the codebase has friendly names).
export type Channel = Database["public"]["Tables"]["channels"]["Row"];
export type Short = Database["public"]["Tables"]["shorts"]["Row"];
export type ShortAltTitle =
  Database["public"]["Tables"]["short_alt_titles"]["Row"];
export type Review = Database["public"]["Tables"]["reviews"]["Row"];
export type UploadRun = Database["public"]["Tables"]["upload_runs"]["Row"];
export type ImportBatch =
  Database["public"]["Tables"]["import_batches"]["Row"];
export type ChannelMember =
  Database["public"]["Tables"]["channel_members"]["Row"];

export type ShortStatus =
  | "draft"
  | "needs_review"
  | "approved"
  | "scheduled"
  | "live"
  | "failed";
